# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Mastercard', 'mastercard'), ('American Express', 'amex'), ('Maestro', 'maestro'), ('Visa', 'visa'), ('Visa Electron', 'visa_electron')], default='mastercard', max_length=6),
        ),
    ]
