# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv_number',
            field=models.CharField(max_length=3),
        ),
    ]
