# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0002_auto_20180228_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
