# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0004_auto_20180328_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirydate',
            field=models.CharField(max_length=7),
        ),
    ]
