# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180316_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
    ]
