# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180320_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='manager', max_length=30, verbose_name='role'),
        ),
    ]
