# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createdby',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
