# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_employeeform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeform',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmployeeForm',
        ),
    ]
