# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_project_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createdby',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
