# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20180216_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=30)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('spendtime', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
