# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
