# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20180215_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee_id',
            field=models.EmailField(default='prpatidar3232@yopmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='discription',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='discription',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='system.Project'),
        ),
    ]
