# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20180215_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee_id',
            field=models.EmailField(max_length=30),
        ),
    ]
