# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20180220_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimatetime',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='spendtime',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
