# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20180220_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='employee_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='system.Project'),
        ),
    ]
