# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20180220_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='employee_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project_id',
            field=models.IntegerField(),
        ),
    ]
