# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='reject_comment',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
