# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20180305_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
