# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_timesheet_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approvaldate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
