# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('discription', models.TextField(max_length=100)),
                ('status', models.CharField(blank=True, default='Pending', max_length=30)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('createdby', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('discription', models.TextField(max_length=100)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=30)),
                ('estimatetime', models.CharField(blank=True, max_length=10, null=True)),
                ('spendtime', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
