# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180223_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createdby',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
