# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hourlyrate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
