# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180227_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hourlyrate',
            field=models.IntegerField(blank=True),
        ),
    ]
