# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180305_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hourlyrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
