# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180306_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createdby',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
