# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180329_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Daliy', 'Daliy'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10, null=True),
        ),
    ]
